### ISSUE TITLE
[Question about details of paper] Why we choose the last token or the mean of token embedding as the input to the downstream models?

### ISSUE THREAD

**Issue by Weibin44** [yuhui-zh15/VLMClassifier#2]
Hi Yuhui, 

Thanks for your great work! I have a question about the details, hope you can help me to figure it out:
1. Why we use the last token or average of the token embs instead of the embs of generated text? Is there any key difference between them?

Thanks for your help in advance!

**Comment by yuhui-zh15** [comment]
Thanks for your interest in my work!

The reason for using the last token or the average of the token embeddings instead of the embeddings of the generated text is to understand whether the necessary information is preserved in the VLM’s embedding space. This experiment helps us determine why VLMs cannot generate correct class names directly.

By probing the last token or the averaged embeddings, we can see if the information required for classification is present but not effectively utilized during the generation process. Our analysis shows that while this information is preserved, it is not decoded correctly when generating text, leading to poor classification performance. This insight helps us improve the VLM’s ability to utilize its latent space more effectively for classification tasks.

I hope this clarifies the reasoning behind the experiment.

**Comment by Weibin44** [comment]
Thanks for your reply! It is very helpful!
